# .github/workflows/daily_run.yml

name: Run Python Script Daily # Name of the workflow visible on GitHub Actions tab

on:
  schedule:
    # Runs 'at 05:00 UTC' every day. You can adjust the time.
    # Use crontab syntax: minute hour day(month) month day(week)
    # Example: '0 8 * * *' runs at 8:00 AM UTC daily
    # Example: '30 18 * * 1-5' runs at 6:30 PM UTC on weekdays (Mon-Fri)
    # Use https://crontab.guru/ to help generate schedules.
    - cron: '0 5 * * *'
  workflow_dispatch: # Allows you to manually trigger the workflow from the Actions tab

jobs:
  build: # You can name this job anything (e.g., run_script)
    runs-on: ubuntu-latest # Specifies the runner environment

    steps:
      # Step 1: Check out the repository code
      - name: Check out repository code
        uses: actions/checkout@v4 # Action to get your code onto the runner

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Specify the Python version you want to use

      # Step 3: (Optional) Install dependencies if your script needs them
      # If you have a requirements.txt file, uncomment the next two lines:
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      # Step 4: Run the Python script
      - name: Run Python script
        run: python main.py # Command to execute your script
        # If your script needs environment variables (e.g., API keys),
        # you can set them using GitHub Secrets (see Step 6) like this:
        # env:
        #   MY_API_KEY: ${{ secrets.YOUR_SECRET_NAME }}